package com.juaracoding.telemarketing.utils;

public enum TestScenarios {
	
	T1("URL Salah"),
	T2("URL Benar"),
	T3("Input invalid username and password"),
	T4("Input null username and password"),
	T5("Input valid username and password"),
	T6("Input valid username dengan ignore lettercase"),
	T7("Logout from profile"),
	T8("Input valid username dengan uppercase"),
	T9("Halaman Dashboard telemarketing"),
	T10("Input field search (Task New)"),
	T11("Click search (Task New)"),
	T12("Next Page (Task New)"),
	T13("Click activity (Task New)"), 
	T14("Input status acitivity invalid (Task New)"),
	T15("Dropdown Tersambung, Diangkat, Setuju (Task New)"),
	T16("Dropdown Tersambung, Diangkat, Follow Up (Task New)"),
	T17("Dropdown Tersambung, Diangkat, Tolak (Task New)"),
	T18("Dropdown Tersambung, Diangkat, Berhasil (Task New)"),
	T19("Dropdown Tersambung, Diangkat, Tidak Berhasil (Task New)"),
	T20("Dropdown Tersambung, Salah Sambung (Task New)"),
	T21("Dropdown Tersambung, Tidak Diangkat (Task New)"),
	T22("Dropdown Tidak Tersambung, Nomer Salah (Task New)"),
	T23("Dropdown Tidak Tersambung, Mailbox (Task New)"),
	T24("Dropdown Tidak Tersambung, Invalid Number(Task New)"),
	T25("Dropdown Tidak Tersambung, Telepon Not Register (Task New)"),
	T26("Input field request phone (Task New)"),
	T27("Input field wa (Task New)"),
	T28("Input field wa invalid (number phone wa input by alphabet) (Task New)"),
	T29("Show page (Task New)"),
	T30("Input field search (Follow Up) "),
	T31("Click search (Follow Up) "),
	T32("Next page (Follow Up) "),
	T33("Click activity (Follow Up)"),
	T34("Input status acitivity invalid (Follow Up)"),
	T35("Dropdown Tersambung, Diangkat, Setuju (Follow Up)"),
	T36("Dropdown Tersambung, Diangkat, Follow Up (Follow Up)"),
	T37("Dropdown Tersambung, Diangkat, Tolak (Follow Up)"),
	T38("Dropdown Tersambung, Diangkat, Berhasil (Follow Up)"),
	T39("Dropdown Tersambung, Diangkat, Tidak Berhasil (Follow Up)"),
	T40("Dropdown Tersambung, Salah Sambung (Follow Up)"),
	T41("Dropdown Tersambung, Tidak Diangkat (Follow Up)"),
	T42("Dropdown Tidak Tersambung, Nomer Salah (Follow Up)"),
	T43("Dropdown Tidak Tersambung, Mailbox (Follow Up)"),
	T44("Dropdown Tidak Tersambung, Invalid Number (Follow Up)"),
	T45("Dropdown Tidak Tersambung, Telepon Not Register (Follow Up)"),
	T46("Input field request phone (Follow Up)"),
	T47("Input field wa (Follow Up)"),
	T48("Input field wa invalid (number phone wa input by alphabet) (Follow Up)"),
	T49("Show page (Follow Up)"),
	T50("Input field search (Final)"),
	T51("Click search (Final)"),
	T52("Next page (Final)"),
	T53("Click activity (Final)"),
	T54("Show page (Final)"),
	T55("Input field search (Data All) "),
	T56("Click search (Data All) "),
	T57("Filter search null (Data All)"),
	T58("Filter search (Data All)"),
	T59("Next page (Data All) "),
	T60("Click activity (Data All)"),
	T61("Input status acitivity invalid (Data All)"),
	T62("Dropdown Tersambung, Diangkat, Setuju (Data All)"),
	T63("Dropdown Tersambung, Diangkat, Follow Up (Data All)"),
	T64("Dropdown Tersambung, Diangkat, Tolak (Data All)"),
	T65("Dropdown Tersambung, Diangkat, Berhasil (Data All)"),
	T66("Dropdown Tersambung, Diangkat, Tidak Berhasil (Data All)"),
	T67("Dropdown Tersambung, Salah Sambung (Data All)"),
	T68("Dropdown Tersambung, Tidak Diangkat (Data All)"),
	T69("Dropdown Tidak Tersambung, Nomer Salah (Data All)"),
	T70("Dropdown Tidak Tersambung, Mailbox (Data All)"),
	T71("Dropdown Tidak Tersambung, Invalid Number (Data All)"),
	T72("Dropdown Tidak Tersambung, Telepon Not Register (Data All)"),
	T73("Input field request phone (Data All)"),
	T74("Input field wa (Data All)"),
	T75("Input field wa invalid (number phone wa input by alphabet) (Data All)"),
	T76("Show page (Data All)"),
	T77("Input field search (Task New Developer)"),
	T78("Click search (Task New Developer)"),
	T79("Next Page (Task New Developer)"),
	T80("Click activity (Task New Developer)"), 
	T81("Input status acitivity invalid (Task New Developer)"),
	T82("Dropdown Tersambung, Diangkat, Setuju (Task New Developer)"),
	T83("Dropdown Tersambung, Diangkat, Follow Up (Task New Developer)"),
	T84("Dropdown Tersambung, Diangkat, Tolak (Task New Developer)"),
	T85("Dropdown Tersambung, Diangkat, Berhasil (Task New Developer)"),
	T86("Dropdown Tersambung, Diangkat, Tidak Berhasil (Task New Developer)"),
	T87("Dropdown Tersambung, Salah Sambung (Task New Developer)"),
	T88("Dropdown Tersambung, Tidak Diangkat (Task New Developer)"),
	T89("Dropdown Tidak Tersambung, Nomer Salah (Task New Developer)"),
	T90("Dropdown Tidak Tersambung, Mailbox (Task New Developer)"),
	T91("Dropdown Tidak Tersambung, Invalid Number(Task New Developer)"),
	T92("Dropdown Tidak Tersambung, Telepon Not Register (Task New Developer)"),
	T93("Input field request phone (Task New Developer)"),
	T94("Input field wa (Task New Developer)"),
	T95("Input field wa invalid (number phone wa input by alphabet) (Task New Developer)"),
	T96("Show page (Task New Developer)"),
	T97("Input field search (Task Follow Up Dev)"),
	T98("Click search (Task Follow Up Dev)"),
	T99("Next Page (Task Follow Up Dev)"),
	T100("Click activity (Task Follow Up Dev)"), 
	T101("Input status acitivity invalid (Task Follow Up Dev)"),
	T102("Dropdown Tersambung, Diangkat, Setuju (Task Follow Up Dev)"),
	T103("Dropdown Tersambung, Diangkat, Follow Up (Task Follow Up Dev)"),
	T104("Dropdown Tersambung, Diangkat, Tolak (Task Follow Up Dev)"),
	T105("Dropdown Tersambung, Diangkat, Berhasil (Task Follow Up Dev)"),
	T106("Dropdown Tersambung, Diangkat, Tidak Berhasil (Task Follow Up Dev)"),
	T107("Dropdown Tersambung, Salah Sambung (Task Follow Up Dev)"),
	T108("Dropdown Tersambung, Tidak Diangkat (Task Follow Up Dev)"),
	T109("Dropdown Tidak Tersambung, Nomer Salah (Task Follow Up Dev)"),
	T110("Dropdown Tidak Tersambung, Mailbox (Task Follow Up Dev)"),
	T111("Dropdown Tidak Tersambung, Invalid Number(Task Follow Up Dev)"),
	T112("Dropdown Tidak Tersambung, Telepon Not Register(Task Follow Up Dev)"),
	T113("Input field request phone (Task Follow Up Dev)"),
	T114("Input field wa (Task Follow Up Dev)"),
	T115("Input field wa invalid (number phone wa input by alphabet) (Task Follow Up Dev)"),
	T116("Show page (Task Follow Up Dev)"),
	T117("Input field search (Data All Dev)"),
	T118("Click search (Data All Dev)"),
	T119("Next Page (Data All Dev)"),
	T120("Click activity (Data All Dev)"), 
	T121("Input status acitivity invalid (Data All Dev)"),
	T122("Dropdown Tersambung, Diangkat, Setuju (Data All Dev)"),
	T123("Dropdown Tersambung, Diangkat, Follow Up (Data All Dev)"),
	T124("Dropdown Tersambung, Diangkat, Tolak (Data All Dev)"),
	T125("Dropdown Tersambung, Diangkat, Berhasil (Data All Dev)"),
	T126("Dropdown Tersambung, Diangkat, Tidak Berhasil (Data All Dev)"),
	T127("Dropdown Tersambung, Salah Sambung (Data All Dev)"),
	T128("Dropdown Tersambung, Tidak Diangkat (Data All Dev)"),
	T129("Dropdown Tidak Tersambung, Nomer Salah (Data All Dev)"),
	T130("Dropdown Tidak Tersambung, Mailbox (Data All Dev)"),
	T131("Dropdown Tidak Tersambung, Invalid Number(Data All Dev)"),
	T132("Dropdown Tidak Tersambung, Telepon Not Register(Data All Dev)"),
	T133("Input field request phone (Data All Dev)"),
	T134("Input field wa (Data All Dev)"),
	T135("Input field wa invalid (number phone wa input by alphabet) (Data All Dev)"),
	T136("Click export (Task New Dev) "),
	T137("Click export (Task Follow Up Dev) "),
	T138("Click export (Data All Dev) ");
	
	private String testName;
	
	TestScenarios(String value) {
		testName = value;
	}
	
	public String getTestName() {
		return testName;
	}

}
